name: renotrack
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.4
  uuid: ^4.5.1
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/images/renotrack_logo.png
    - assets/icon/app_icon.png
    - assets/splash/splash_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#3f51b5"
  image: assets/splash/splash_icon.png
  android: true
  ios: true
  android_gravity: center
